variables:
    VIRTUALENV_NO_DOWNLOAD: "1"

########################################################################################################################
# Basic declarations
.requires-python: &requires-python
    tags:
        - python

.python2-xenial: &python2-xenial
    image: $CI_REGISTRY/ginger/base/ubuntu_xenial_python2:latest

########################################################################################################################
# Individual jobs
test:
    <<: *requires-python
    <<: *python2-xenial
    before_script:
        - pip install tox "virtualenv<=16.2.0"
    script:
        - tox
