variables:
    DOCKER_REGISTRY: "archive.nic.cz:5000"
    # Set up pip cache shared between all jobs of the project.
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    TOX_PARALLEL_NO_SPINNER: 1

cache:
    paths:
        - .cache/pip

########################################################################################################################
# Basic declarations
.py38: &py38
    image: "$DOCKER_REGISTRY/python/tox:3.8"

.test: &test
    script:
        - tox

########################################################################################################################
# Individual jobs
licensing:
    script:
        - git clone git@gitlab.office.nic.cz:internal-tools/license-check.git --single-branch --depth 1
        - ./license-check/license-check.sh -v

test:py38:
    <<: *test
    <<: *py38
