stages:
    - analysis

########################################################################################################################
# Basic declarations
.requires-python: &requires-python
    tags:
        - python

.python2-xenial: &python2-xenial
    image: cznic/ubuntu_xenial_python2:latest

########################################################################################################################
# Individual jobs
quality:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install tox
    script:
        - tox -e quality
