stages:
    - analysis

########################################################################################################################
# Basic declarations
.requires-python: &requires-python
    tags:
        - python

.python2-xenial: &python2-xenial
    image: cznic/ubuntu_xenial_python2:latest

########################################################################################################################
# Individual jobs
isort:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install isort
        - pip list
    script: "make check-isort"

flake8:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install flake8
        - pip list
    script: "make check-flake8"

pydocstyle:
    <<: *requires-python
    <<: *python2-xenial
    stage: analysis
    before_script:
        - pip install pydocstyle
        - pip list
    script: "make check-doc"
