stages:
    - analysis

isort:
    image: cznic/ubuntu_python_runner:latest
    stage: analysis
    before_script:
        - pip install isort
        - pip list
    script: "make check-isort"

flake8:
    image: cznic/ubuntu_python_runner:latest
    stage: analysis
    before_script:
        - pip install flake8
        - pip list
    script: "make check-flake8"

pydocstyle:
    tags:
        - python2
    stage: analysis
    before_script:
        - pip install pydocstyle
        - pip list
    script: "make check-doc"
